/* Autogenerated by png2wx.pl on Fri May  4 15:19:59 2012 */
#ifndef ICONS_H
#define ICONS_H 1

#include <wx/wxprec.h>
#ifndef WX_PRECOMP
#include <wx/wx.h>
#endif

extern void initialize_images(void);

extern wxBitmap* _img_survey;
extern wxBitmap* _img_survey_pi;
extern wxBitmap* _img_survey_recording;
extern wxBitmap* _img_survey_paused;
extern wxBitmap* _img_minus;
extern wxBitmap* _img_plus;

#ifdef SURVEY_USE_SVG
extern wxString _svg_survey;
extern wxString _svg_survey_toggled;
#endif

#endif /* ICONS_H */
