/* Autogenerated by png2wx.pl on Sat Feb 18 11:44:00 2012 */
#ifndef ICONS_H
#define ICONS_H 1

#include <wx/wxprec.h>
#ifndef WX_PRECOMP
#	include <wx/wx.h>
#endif

extern void initialize_images(void);

extern wxBitmap *_img_survey;
extern wxBitmap *_img_survey_pi;

#endif /* ICONS_H */
