---
name: test-clang-format

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: DoozyX/clang-format-lint-action@v0.13
        with:
          source: './src ./include'
          exclude: './src/dashboardskgui.cpp ./include/dashboardskgui.h'
          extensions: 'h,cpp'
          clangFormatVersion: 13
          style: file
...
