---
# yamllint disable rule:line-length
name: Windows 32bit build

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'manual/**'
    tags:
      - '*'
  pull_request:
    branches:
      - master
    paths-ignore:
      - 'manual/**'

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}


jobs:
  build:
    runs-on: ${{ matrix.runner }}
    name: ${{ matrix.name }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Windows MSVC
            runner: windows-latest
            no_sudo: 1
            # TODO: Tests don't link on Windows, investigate and fix later
            cmake_defines: -T v143 -DCMAKE_GENERATOR_PLATFORM=win32 -DWITH_TESTS=OFF -DCMAKE_CXX_STANDARD=17

    env:
      wxGTK_VERSION: ${{ matrix.gtk_version && matrix.gtk_version || 3 }}

    # Use bash as the shell, even under MSW where the default is PowerShell.
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      # required for CMake to find Ninja
      - name: "[Windows] Set up MSVC Developer Command Prompt"
        if: runner.os == 'Windows'
        uses: seanmiddleditch/gha-setup-vsdevenv@v3
        with:
          host_arch: x86
          arch: win32

      - name: "[Windows] Dependencies, configure, build"
        if: runner.os == 'Windows'
        run: |
          call buildwin/win_deps.bat
          cmake -A win32 -B build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} ${{ matrix.cmake_defines }}
          cmake --build build --config ${{env.BUILD_TYPE}}
        shell: cmd
      - name: "[Windows] Publish to Cloudsmith"
        if: runner.os == 'Windows'
        run: |
          cd build
          .\upload.bat
        shell: cmd
...
